"""empty message

Revision ID: 5034f7d980cd
Revises: 15cf6bdaa482
Create Date: 2021-08-18 13:03:36.026057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5034f7d980cd'
down_revision = '15cf6bdaa482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_model', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('todo_model', sa.Column('shared', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_model', 'shared')
    op.drop_column('todo_model', 'owner')
    # ### end Alembic commands ###
