"""empty message

Revision ID: f3b95a3034da
Revises: 5034f7d980cd
Create Date: 2022-06-20 09:31:30.986745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b95a3034da'
down_revision = '5034f7d980cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xai_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('class_ground_truth', sa.Integer(), nullable=True),
    sa.Column('has_prediction', sa.Boolean(), nullable=True),
    sa.Column('prediction_result', sa.Integer(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('optical_height_max', sa.Float(), nullable=True),
    sa.Column('optical_height_min', sa.Float(), nullable=True),
    sa.Column('optical_height_mean', sa.Float(), nullable=True),
    sa.Column('optical_height_var', sa.Float(), nullable=True),
    sa.Column('center_x', sa.Float(), nullable=True),
    sa.Column('center_y', sa.Float(), nullable=True),
    sa.Column('mass_center_x', sa.Float(), nullable=True),
    sa.Column('mass_center_y', sa.Float(), nullable=True),
    sa.Column('mass_center_shift', sa.Float(), nullable=True),
    sa.Column('radius_mean', sa.Float(), nullable=True),
    sa.Column('radius_variance', sa.Float(), nullable=True),
    sa.Column('perimeter', sa.Float(), nullable=True),
    sa.Column('circularity', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('solidity', sa.Float(), nullable=True),
    sa.Column('equivalent_diameter', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('biconcavity', sa.Float(), nullable=True),
    sa.Column('sphericity', sa.Float(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('dissimilarity', sa.Float(), nullable=True),
    sa.Column('homogeneity', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todo_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shared', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todo_model_pkey')
    )
    op.drop_table('xai_model')
    # ### end Alembic commands ###
