import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import PrimeVue from "primevue/config";
import Button from "primevue/button";
import InputText from "primevue/inputtext";
import Card from "primevue/card";
import DataView from "primevue/dataview";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import ColumnGroup from "primevue/columngroup";
import Dropdown from "primevue/dropdown";
import Accordion from "primevue/accordion";
import AccordionTab from "primevue/accordiontab";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import Toolbar from "primevue/toolbar";
import CascadeSelect from "primevue/cascadeselect";
import Row from "primevue/row";
import Image from "primevue/image";
import Galleria from "primevue/galleria";
import ApexCharts from "apexcharts";
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
import VueVega from "vue-vega";
import Echarts from "echarts";
import Plotly from "plotly.js-dist-min";
import Vue from "vue";
import Listbox from "primevue/listbox";
import Dialog from "primevue/dialog";
import Carousel from "primevue/carousel";

import "primevue/resources/themes/saga-blue/theme.css";
import "primevue/resources/primevue.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";

const app = createApp(App);

app.use(store);
app.use(router);
app.use(PrimeVue);

app.component("Button", Button);
app.component("InputText", InputText);
app.component("Card", Card);
app.component("DataView", DataView);
app.component("DataTable", DataTable);
app.component("Column", Column);
app.component("ColumnGroup", ColumnGroup);
app.component("Dropdown", Dropdown);
app.component("Accordion", Accordion);
app.component("AccordionTab", AccordionTab);
app.component("TabView", TabView);
app.component("TabPanel", TabPanel);
app.component("Toolbar", Toolbar);
app.component("CascadeSelect", CascadeSelect);
app.component("Row", Row);
app.component("Image", Image);
app.component("Galleria", Galleria);
app.component("ApexCharts", ApexCharts);
app.component("Splitter", Splitter);
app.component("SplitterPanel", SplitterPanel);
app.component("VueVega", VueVega);
app.component("Echarts", Echarts);
app.component("Plotly", Plotly);
app.component("Vue", Vue);
app.component("Listbox", Listbox);
app.component("Carousel", Carousel);
app.mount("#app");
app.mount("#vis");
app.component("Dialog", Dialog);
